"""Emit a TS module embedding the real chest X-ray data URLs as named exports.

This lets the frontend bundle real de-identified radiographs (public COVID-19
chest X-ray dataset, ieee8023/covid-chestxray-dataset) instead of synthetic SVG
cartoons, so the DenseNet-121 ONNX model produces meaningful activations.
"""
import os

IN_DIR = os.path.join('src', 'data', 'xray_b64')
OUT_FILE = os.path.join('src', 'data', 'realXrays.ts')

NAMES = ['pneumonia', 'cardiomegaly', 'copd', 'appendicitis']

HEADER = """/**
 * Real de-identified chest radiographs used for the flagship demo cases.
 *
 * Source: COVID-19 Image Data Collection (ieee8023/covid-chestxray-dataset),
 * a public dataset of de-identified chest radiographs. Images were resized to
 * 448x448 grayscale JPEG and embedded as data URLs so the frontend ships real
 * model inputs without a network fetch. These replace the previous synthetic
 * SVG cartoons, which produced meaningless DenseNet-121 probabilities.
 *
 * GENERATED by scripts/emit_real_xrays.py — do not edit by hand.
 */
"""

def main():
    parts = [HEADER]
    for name in NAMES:
        path = os.path.join(IN_DIR, name + '.txt')
        with open(path, 'r') as f:
            data_url = f.read().strip()
        const_name = 'REAL_XRAY_' + name.upper()
        parts.append('export const %s =\n  \'%s\';\n' % (const_name, data_url))

    # Convenience map keyed by the scenario image-type token.
    parts.append(
        "export const REAL_XRAYS: Record<'pneumonia' | 'cardiomegaly' | 'copd' | 'appendicitis', string> = {\n"
        "  pneumonia: REAL_XRAY_PNEUMONIA,\n"
        "  cardiomegaly: REAL_XRAY_CARDIOMEGALY,\n"
        "  copd: REAL_XRAY_COPD,\n"
        "  appendicitis: REAL_XRAY_APPENDICITIS,\n"
        "};\n"
    )

    with open(OUT_FILE, 'w') as f:
        f.write('\n'.join(parts))
    print('Wrote', OUT_FILE, os.path.getsize(OUT_FILE) // 1024, 'KB')

if __name__ == '__main__':
    main()
